version: '2'
services:
    accuestimator-app:
        image: accuestimator
        external_links:
            - accuestimator-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=accuestimator
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    accuestimator-mongodb:
        extends:
            file: mongodb.yml
            service: accuestimator-mongodb
