version: '2'
services:
    accuestimator-mongodb:
        container_name: accuestimator-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/accuestimator/mongodb/:/data/db/
